import tkinter as tk

top = tk.Tk()
arrow = tk.Button(top, text = "arrow", cursor="arrow")
circle = tk.Button(top, text = "circle", cursor="circle")
clock = tk.Button(top, text = "clock", cursor="clock")
cross = tk.Button(top, text = "cross", cursor="cross")
dotbox = tk.Button(top, text = "dotbox", cursor="dotbox")
exchange = tk.Button(top, text = "exchange", cursor="exchange")
fleur = tk.Button(top, text = "fleur", cursor="fleur")
heart = tk.Button(top, text = "heart", cursor="heart")
man = tk.Button(top, text = "man", cursor="man")
mouse = tk.Button(top, text = "mouse", cursor="mouse")
pirate = tk.Button(top, text = "pirate", cursor="pirate")
plus = tk.Button(top, text = "plus", cursor="plus")
shuttle = tk.Button(top, text = "shuttle", cursor="shuttle")
sizing = tk.Button(top, text = "sizing", cursor="sizing")
spider = tk.Button(top, text = "spider", cursor="spider")
spraycan = tk.Button(top, text = "spraycan", cursor="spraycan")
star = tk.Button(top, text = "star", cursor="star")
target = tk.Button(top, text = "target", cursor="target")
tcross = tk.Button(top, text = "tcross", cursor="tcross")
trek = tk.Button(top, text = "trek", cursor="trek")
watch = tk.Button(top, text = "watch", cursor="watch")

arrow.pack()
circle.pack()
clock.pack()
cross.pack()
dotbox.pack()
exchange.pack()
fleur.pack()
heart.pack()
man.pack()
mouse.pack()
pirate.pack()
plus.pack()
shuttle.pack()
sizing.pack()
spider.pack()
spraycan.pack()
star.pack()
target.pack()
tcross.pack()
trek.pack()
watch.pack()

top.mainloop()

